/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

import java.util.Random;

/**
 *
 * @author danie
 */
public class Dado6 extends javax.swing.JFrame {

    /**
     * Creates new form Dado100
     */
    public Dado6() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("FEROVA GAME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tirar_Dado1 = new javax.swing.JLabel();
        jLabelnumdado = new javax.swing.JLabel();
        Dado_G = new javax.swing.JButton();
        Atacar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tirar_Dado1.setBackground(new java.awt.Color(102, 255, 102));
        Tirar_Dado1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 2, 24)); // NOI18N
        Tirar_Dado1.setForeground(new java.awt.Color(255, 0, 0));
        Tirar_Dado1.setText("TIRAR DADO 6");
        getContentPane().add(Tirar_Dado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 310, 70));

        jLabelnumdado.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabelnumdado.setForeground(new java.awt.Color(255, 0, 51));
        jLabelnumdado.setText("----------");
        getContentPane().add(jLabelnumdado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        Dado_G.setBackground(new java.awt.Color(102, 255, 102));
        Dado_G.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Dado_G.setForeground(new java.awt.Color(255, 0, 51));
        Dado_G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/dado-imagen-animada-0104.gif"))); // NOI18N
        Dado_G.setActionCommand("Ver Reportes");
        Dado_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dado_GActionPerformed(evt);
            }
        });
        getContentPane().add(Dado_G, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 330, 300));

        Atacar.setBackground(new java.awt.Color(0, 0, 0));
        Atacar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 2, 24)); // NOI18N
        Atacar.setForeground(new java.awt.Color(255, 0, 0));
        Atacar.setText("Tirar");
        Atacar.setActionCommand("Ver Reportes");
        Atacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtacarActionPerformed(evt);
            }
        });
        getContentPane().add(Atacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 180, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/Nacis.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Dado_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dado_GActionPerformed
       String num = String.valueOf(valorDado());
         jLabelnumdado.setText(num);

    }//GEN-LAST:event_Dado_GActionPerformed

    private void AtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtacarActionPerformed
         JuegoTableros entrada3 = new JuegoTableros();
        entrada3.show();
        entrada3.setSize(1290, 1000);
            dispose();  
        this.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_AtacarActionPerformed

     public int valorDado(){
        int valor;
        Random n = new Random();
        valor = n.nextInt(5);

        return valor;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dado6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dado6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dado6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dado6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dado6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atacar;
    public static javax.swing.JButton Dado_G;
    private javax.swing.JLabel Tirar_Dado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelnumdado;
    // End of variables declaration//GEN-END:variables
}
