/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

import ClasesdelProyecto.Casilla;
import ClasesdelProyecto.CasillaMontaña;
import ClasesdelProyecto.CasillaAgua;
import ClasesdelProyecto.CasillaTerreno;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class JuegoTableros extends javax.swing.JFrame {
    int turno, contp, contmp;
    boolean gano= false;
    //String [] botones = { " 4*4", " 4*6", "8*9" };
 


  Casilla[][] tablero;
    /**
     * constructor
     * Creates new form JuegoTableros
     */
    public JuegoTableros() {
        initComponents();
          this.setLocationRelativeTo(null);
            setSize(1290, 1000);
        
          turno = contp = contmp = 1;
        //  Object [] botones = {"4x4", " 4*6", "8*9" };
         // int variable = JOptionPane.showOptionDialog (null, " Qué tablero desea?", "Elija uno", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null/*icono*/, botones, botones[0]);

        setTitle("FEROVA GAME");
        //tablero = new Casilla[8][8];
           
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDado3 = new javax.swing.JButton();
        jButtonDado101 = new javax.swing.JButton();
        jButtonDado7 = new javax.swing.JButton();
        jButtonHaciaE = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton8x9 = new javax.swing.JButton();
        jButton4x4 = new javax.swing.JButton();
        jButton6x4 = new javax.swing.JButton();
        panelTablero = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDado3.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDado3.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButtonDado3.setForeground(new java.awt.Color(51, 255, 0));
        jButtonDado3.setText("DADO 3");
        jButtonDado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDado3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, 160, 80));

        jButtonDado101.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDado101.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButtonDado101.setForeground(new java.awt.Color(51, 255, 0));
        jButtonDado101.setText("DADO 100");
        jButtonDado101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDado101ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDado101, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 160, 80));

        jButtonDado7.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDado7.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButtonDado7.setForeground(new java.awt.Color(51, 255, 0));
        jButtonDado7.setText("DADO 6");
        jButtonDado7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDado7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, 160, 80));

        jButtonHaciaE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonHaciaE.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        jButtonHaciaE.setForeground(new java.awt.Color(0, 255, 0));
        jButtonHaciaE.setText("Fin batalla");
        jButtonHaciaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHaciaEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHaciaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 800, 200, 80));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Generar Tablero");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 340, 40));

        jButton8x9.setBackground(new java.awt.Color(255, 255, 255));
        jButton8x9.setFont(new java.awt.Font("Dubai Medium", 0, 36)); // NOI18N
        jButton8x9.setForeground(new java.awt.Color(0, 255, 0));
        jButton8x9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/tanquepequeño.jpg"))); // NOI18N
        jButton8x9.setText("8 x 9");
        jButton8x9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8x9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8x9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 340, 150));

        jButton4x4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4x4.setFont(new java.awt.Font("Dubai Medium", 0, 36)); // NOI18N
        jButton4x4.setForeground(new java.awt.Color(0, 255, 0));
        jButton4x4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/tanquepequeño.jpg"))); // NOI18N
        jButton4x4.setText("4 x 4");
        jButton4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4x4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 340, 160));

        jButton6x4.setBackground(new java.awt.Color(255, 255, 255));
        jButton6x4.setFont(new java.awt.Font("Dubai Medium", 0, 36)); // NOI18N
        jButton6x4.setForeground(new java.awt.Color(0, 255, 0));
        jButton6x4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/avionpequeño.jpg"))); // NOI18N
        jButton6x4.setText("6  x 4");
        jButton6x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6x4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 270, 140));

        panelTablero.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(panelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/FinesseGrande.png"))); // NOI18N
        getContentPane().add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    /**
     * Método para ir hacia las opciones finales del juego
     * @param evt 
     */
    private void jButtonHaciaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHaciaEActionPerformed
        // TODO add your handling code here:
        OpcionesFinales entrada3 = new OpcionesFinales();
        entrada3.show();
        entrada3.setSize(825, 866);
            dispose();    
    }//GEN-LAST:event_jButtonHaciaEActionPerformed
    /**
     * Método para mostrar el tablero, código generico
     * @param filas
     * @param columnas 
     */
    public void gTablero(int filas, int columnas){
    BorderLayout b = new BorderLayout(); 
    
       tablero =  new Casilla[filas][columnas];
        int[][] juego = new int[filas][columnas];
        Random n = new Random();
         boolean blanco = true;
         System.out.println("filas" + filas);
        for (int i = 0; i<filas; i++){
            for (int j = 0; j<columnas; j++){
                
                int c = (int)((Math.random()*3)+1);
                System.out.println(c);
                switch(c){
                    case 1: 
                        juego[i][j]= 1;
                        tablero[i][j] = new Casilla ();
                         tablero[i][j].setBounds((50*j), 50*i, 50, 50);
                          tablero[i][j]= new CasillaTerreno();
                          break;
                    case 2:
                        juego[i][j]= 2;
                        tablero[i][j] = new Casilla ();
                         tablero[i][j].setBounds((50*j), 50*i, 50, 50);
                          tablero[i][j]= new CasillaMontaña();
                          break;
                    case 3:
                        juego[i][j]= 3;
                        tablero[i][j] = new Casilla ();
                         tablero[i][j].setBounds((50*j), 50*i, 50, 50);
                          tablero[i][j]= new CasillaAgua();
                    break;
                    default:
                    break;
                    
                }
                /*blanco = !blanco;
                tablero[i][j] = new Casilla ();
               tablero[i][j].setSize(50, 50);
                if (blanco)
                    tablero[i][j].setBackground(Color.white);
                else
                    tablero[i][j].setBackground(Color.white);*/
               // blanco = !blanco;
             //tablero[i][j]= new CasillaTerreno();
              // tablero[i][j].setSize(50, 50);

                
               
             //   if (blanco)
               //     tablero[i][j] = new CasillaMontaña();
              //  else
                //    tablero[i][j] = new CasillaAgua();

                
                tablero[i][j].setVisible(true);

                tablero[i][j].setBounds((50*j), 50*i, 50, 50);
               

              //  this.remove(panelTablero);
               //  this.add(tablero[i][j], BorderLayout.CENTER);
               //this.add(panelTablero);
               
                    panelTablero.add(tablero[i][j]);
                   //  tablero[i][j].addActioLsitener(accion);
               //  panelTablero.removeAll();
       //     panelTablero.validate();
       panelTablero.updateUI();
       panelTablero.setLayout(new GridLayout(filas, columnas));
            panelTablero.repaint();
         //   tablero[i][j].removeAll();
           //tablero[i][j].repaint();
            
         
     
           
            }
           
            blanco = !blanco;
        }
          
        
        int d = (int) (Math.random()*4);
        int d2 = (int) (Math.random()*4);
              ImageIcon tanque = new ImageIcon("src/ImagenesD/tanquepequeño.jpg");
        Icon iconoTanque = new ImageIcon(tanque.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        tablero[d][d2].setIcon(iconoTanque);
        juego[d][d2] = 5;
        
         int a = (int) (Math.random()*4);
        int a2 = (int) (Math.random()*4);
            ImageIcon avion = new ImageIcon("src/ImagenesD/avionpequeño.jpg");
        Icon iconoAvion = new ImageIcon(avion.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
         tablero[a][a2].setIcon(iconoAvion);
        juego[a][a2] = 4;
        
         int z = (int) (Math.random()*4);
        int z2 = (int) (Math.random()*4);
            ImageIcon avion1 = new ImageIcon("src/ImagenesD/avionpequeño.jpg");
        Icon iconoAvion1 = new ImageIcon(avion1.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
         tablero[z][z2].setIcon(iconoAvion1);
        juego[z][z2] = 4;
        
    /*tablero = new Casilla[filas][columnas];
    int contX=-1,contY=-1;
    for (Casilla[] casillas : tablero) {
        contX++;
        for (Casilla casilla : casillas) {
            contY++;
            casilla = new Casilla();
           casilla.setSize(50, 50);
            //casilla.setVisible(true);
            casilla.setBounds((30), (30), 30, 30);
            panelTablero.add(casilla);
            panelTablero.validate();
            panelTablero.repaint();
           
        }
        
    }*/
}
    
   
    /*public int lanzardado(){
        int numero = 0;
        do{
            numero = (int) (Math.random()*10);
            
                   
                   
            
            
            
            
        }while(numero<1 || numero>6);
        
        
        
        
      return numero;
      
      
      
    } 
    public void generar(){
        for (int i = 0; i < 10; i++) {
            
        }
        
    }    */
    /**
     * Método de prueba para numeros random
     * @param N
     * @param M 
     */
    public void metodoRandom(int N, int M){
        Random n = new Random();
        n.nextInt(5);
        n.nextInt(6);
        
        
    }
    
    private void jButton4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4x4ActionPerformed
        // TODO add your handling code here:
        /*ImageIcon tanque = new ImageIcon("src/ImagenesD/tanquepequeño.jpg");
        Icon iconoTanque = new ImageIcon(tanque.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        tablero[filas][columnas].setIcon(iconoTanque);
        juego[filas][columnas] = 2;*/
        
        gTablero(4, 4);
       
               
        
    }//GEN-LAST:event_jButton4x4ActionPerformed

    private void jButton6x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6x4ActionPerformed
        // TODO add your handling code here:  
       
        gTablero(6, 4);
    }//GEN-LAST:event_jButton6x4ActionPerformed

    private void jButton8x9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8x9ActionPerformed
        // TODO add your handling code here:
         
        gTablero(8, 9);
    }//GEN-LAST:event_jButton8x9ActionPerformed

    private void jButtonDado101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDado101ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Dado100().setVisible(true);
    }//GEN-LAST:event_jButtonDado101ActionPerformed

    private void jButtonDado7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDado7ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Dado6().setVisible(true);
    }//GEN-LAST:event_jButtonDado7ActionPerformed

    private void jButtonDado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDado3ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new Dado3().setVisible(true);
    }//GEN-LAST:event_jButtonDado3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoTableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoTableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoTableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoTableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoTableros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4x4;
    private javax.swing.JButton jButton6x4;
    private javax.swing.JButton jButton8x9;
    private javax.swing.JButton jButtonDado101;
    private javax.swing.JButton jButtonDado3;
    private javax.swing.JButton jButtonDado7;
    private javax.swing.JButton jButtonHaciaE;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables
}
