/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;


import ClasesdelProyecto.EstadisticasV;
import static VistasInterfazD.CrearV.contenedor1;
import static VistasInterfazD.CrearV.jTextFieldNombreV1;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static proyectofinaldaniel.ProyectoFinalDaniel.pathVehiculosD;

/**
 *
 * @author danie
 */
public class VEstadisticas extends javax.swing.JFrame {
private DefaultTableModel modelo;
    int cont = 0; //contador
    /**
     * Constructor de vehículos sus esta
     * Creates new form VEstadisticas
     */
    public VEstadisticas() {
        initComponents();
        setSize(1490, 1200);
        setTitle("FEROVA GAME");
        CargarRegistrarV();
        readBinarioV();
        CargardatosV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonRegresarE = new javax.swing.JButton();
        jButtonSalirE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstadisticasV = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Vehículos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 210, 70));

        jButtonRegresarE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegresarE.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonRegresarE.setForeground(new java.awt.Color(0, 255, 51));
        jButtonRegresarE.setText("Regresar");
        jButtonRegresarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 770, 240, 100));

        jButtonSalirE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalirE.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonSalirE.setForeground(new java.awt.Color(0, 255, 0));
        jButtonSalirE.setText("Salir del Juego");
        jButtonSalirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirE, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 780, 270, 110));

        jTableEstadisticasV.setBackground(new java.awt.Color(255, 255, 255));
        jTableEstadisticasV.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jTableEstadisticasV.setForeground(new java.awt.Color(0, 0, 0));
        jTableEstadisticasV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Nombre", "Puntería", "Ataque", "Defensa", "Velocidad", "CostoV"
            }
        ));
        jScrollPane1.setViewportView(jTableEstadisticasV);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 980, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/FinesseGrande.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para registrar los vehículos
 */
    public void CargarRegistrarV(){
    String datos [][]= {};
    String columna[]= {"Tipo", "Nombre", "Puntería", "Ataque","Defensa","Velocidad", "Costo"};
    String columna1[] = { "V1" };
    
    modelo= new DefaultTableModel(datos, columna);
    jTableEstadisticasV.setModel(modelo);
    
}
/**
 * Método para leerlo Binario
 */
 public void readBinarioV(){
        contenedor1.clear();
        ObjectInputStream binario = null;
        try {
            String nameFile = jTextFieldNombreV1.getText();
            File filevehiculos = new File("VehiculosD");
            
            
            
            for (String string3:filevehiculos.list()) {
                
                binario = new ObjectInputStream(new FileInputStream(pathVehiculosD+string3));
                EstadisticasV d = (EstadisticasV) binario.readObject();
                contenedor1.add(d);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
          //  Logger.getLogger(Registrar.class.getName()).log(Level.SEVERE, null, e);
        } finally {
            try {
                binario.close();
            } catch (IOException e) {
                Logger.getLogger(CrearV.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        
    } 
 /**
  * Método para cargardatos de los vehiculos
  */
 public void CargardatosV(){
                EstadisticasV a;
                //Registrar b;
                for (int i = 0; i < CrearV.contenedor1.size(); i++) {
                    a= (EstadisticasV)CrearV.contenedor1.get(i);
                  //  b= (Registrar) Registrar.contenedor.get(i);
                    modelo.insertRow(cont, new Object []{ });
                    modelo.setValueAt(a.getTipoV(), cont, 0);
                    modelo.setValueAt(a.getNombreV(), cont, 1);
                    modelo.setValueAt(a.getPunteriaV(), cont, 2);
                    modelo.setValueAt(a.getAtaqueV(), cont, 3);
                     modelo.setValueAt(a.getDefensaV(), cont, 4);
                     modelo.setValueAt(a.getVelocidadV(), cont, 5);
                             modelo.setValueAt(a.getCostoV(), cont, 6);
                     
                    
                    
                    
                }
                    
                
                
            }
 /**
  * Método para salir del juego
  * @param evt 
  */
    private void jButtonSalirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirEActionPerformed
/**
 * Método para regresar a Tienda
 * @param evt 
 */
    private void jButtonRegresarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarEActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        new Tienda().setVisible(true);
        setSize(825, 866);
        dispose();
    }//GEN-LAST:event_jButtonRegresarEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEstadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresarE;
    private javax.swing.JButton jButtonSalirE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstadisticasV;
    // End of variables declaration//GEN-END:variables
}
